# The amount of players in each team
# A team may only have 1, 2, 3 or 4 players
teamSize: 1

# The amount of seconds it takes to start the game after the last needed player joins
lobbyCountdown: 20

# The amount of seconds it takes to be able to use /shout again
shoutCooldown: 30

# The time, when a player is eligible for getting a kill
# Example: A player hits another player, if they die in the next n amount of seconds the first player gets the kill
playerTagPeriod: 5

# The hypixel api key, that will be used to fetch some additional data, meaning that the plugin will work just fine without it
# If you want to use this feature, uncomment the field below and replace <key> with your key
#hypixelApiKey: <key>

# Generator settings in solos and doubles
generators1&2:
  # The Forge
  forgeIronCap: 64 # Maximum of 64 iron can be laying in the generator
  forgeGoldCap: 16 # Same as the above, just for gold
  # Diamond generators
  diamondI: 30 # A new diamond every 30 seconds
  diamondII: 23 # ... 23 seconds
  diamondIII: 12 # ... 12 seconds
  diamondCap: 4 # Maximum of 4 diamonds can be laying in the generator
  # Emerald generators
  emeraldI: 60 # A new emerald every 60 seconds
  emeraldII: 45 # ... 45 seconds
  emeraldIII: 30 # ... 30 seconds
  emeraldCap: 2 # Maximum of 2 emeralds can be laying in the generator

# Generator settings in threes and fours
generators3&4:
  # The Forge
  forgeIronCap: 64
  forgeGoldCap: 16
  # Diamond generators
  diamondI: 30
  diamondII: 23
  diamondIII: 12
  diamondCap: 8
  # Emerald generators
  emeraldI: 60
  emeraldII: 45
  emeraldIII: 30
  emeraldCap: 6

# When should each event occur in seconds (from the start of the game)
events:
  diamondII: 360 # 6 minutes into the game
  emeraldII: 720 # 12 minutes into the game
  diamondIII: 1080 # 18 minutes into the game
  emeraldIII: 1440 # 24 minutes into the game
  bedDestruction: 1800 # 30 minutes into the game
  suddenDeath: 2400 # 40 minutes into the game
  gameEnd: 3000 # 50 minutes into the game