# The amount of players in each team
# A team may only have 1, 2, 3 or 4 players
teamSize: 1

# The amount of seconds it takes to start the game after the last needed player joins
lobbyCountdown: 20

# The amount of seconds it takes to be able to use /shout again
shoutCooldown: 30