name: BedWarsRecoded
load: POSTWORLD
version: ${project.version}
main: me.pycrs.bedwarsrecoded.Bedwars
api-version: 1.16
authors: [ Pycrs ]
description: I tried to recode the famous Hypixel Bedwars
website: https://github.com/Pzdrs
commands:
  shout:
    description: Shout command
    usage: /shout <shout message>
  start:
    description: Force start the game
    usage: /start